autocmd BufNewFile,BufRead *.c source ~/.vim/c.vim
autocmd BufNewFile,BufRead *.py source ~/.vim/python.vim
autocmd BufNewFile,BufRead *.sh source ~/.vim/scripts.vim
filetype on
highlight ExtraWhitespace ctermbg=red guibg=red
set colorcolumn=80
syntax on
match ExtraWhitespace /\s\+$/
